version: '3.5'
services:
  api:
    build:
      context: .
      cache_from:
        - &img_tag psychrochartweb/addon:latest
    environment:
      SCAN_INTERVAL: ${SCAN_INTERVAL:-45}
      LOGGING_LEVEL: ${LOGGING_LEVEL:-WARNING}
      PORT: 80
      HA_CONFIG_NAME: ${HA_CONFIG_NAME:-custom_ha_sensors.yaml}
      CUSTOM_FOLDER: /app/custom
    image: *img_tag
    command: poetry run python -m psychrochartweb
    restart: "always"
    ports:
      - 7778:80
    # share volume for chart & HomeAssistant configuration
    volumes:
      - ./custom:/app/custom
      - .:/app
