services:
  api:
    build:
      context: .
      cache_from:
        - &img_tag psychrochartweb/webapp:latest
    environment:
      APP_PORT: 8080
      LOGGING_LEVEL: ${LOGGING_LEVEL:-WARNING}
      HA_CONFIG_NAME: ${HA_CONFIG_NAME:-custom_ha_sensors.yaml}
      CUSTOM_FOLDER: /app/custom
    image: *img_tag
    command: psychrocam
    restart: "always"
    ports:
      - 7778:8080
    # share volume for chart & HomeAssistant configuration
    volumes:
      - ./custom:/app/custom
